version: '2'
services:
  php:
    build: ./php-fpm
    volumes:
      - ./app:/var/www
      - ./php-fpm/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mysql
  server:
    image: nginx:latest
    ports:
      - "8888:80"
    volumes:
      - ./app:/var/www
      - ./nginx/config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3333:3306"
